import Button from "@mui/material/Button";
import type { NextPage } from "next";
import Head from "next/head";
import { WeekForecast } from "../components/week-forecast";
import styles from "../styles/Home.module.css";
import mainStyles from "../styles/mainCard.module.css";
import { useState, MouseEvent, useEffect } from 'react'
import { getData } from "../service/base-service";

const Home: NextPage = () => {
  const [isShown, setIsShown] = useState(false);

  const handleClick = (event: MouseEvent<HTMLButtonElement, Event>) => {
    setIsShown((current: boolean) => !current);
  };
  

  useEffect(() => {
    getData()
  })
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        { !isShown && (
        <div className={`${mainStyles.card} ${mainStyles.mainCard} ${mainStyles.swingBottom}`}>
          <h1>clyma</h1>
          <h3>Updated just now</h3>

          <h1>Paris France</h1>
          <div className={mainStyles.weatherStateContainer}>
            <h1 className={mainStyles.temperatureIndicator}>11°</h1>
            <p>Thunderstorm</p>
            <div>Min 11° | Max:16°</div>
            <p>3% chance of rain</p>
          </div>
          <div className={mainStyles.tableContainer}>
            <table className={mainStyles.table}>
              <colgroup>
                <col className={mainStyles.colRight} />
                <col className={mainStyles.colLeft} />
              </colgroup>
              <tr className={mainStyles.tableText}>
                <td>Humidity</td>
                <td>58%</td>
              </tr>
              <tr>
                <td className={mainStyles.tableText}>Pressure</td>
                <td>1018 mB</td>
              </tr>
              <tr>
                <td className={mainStyles.tableText}>Wind Speed</td>
                <td>15 km/h</td>
              </tr>
            </table>
          </div>
          <Button onClick={(e) => handleClick(e)} variant="contained" size="large" className="mui-button">
              week forecast
            </Button>
        </div>)}
        {
            isShown && (
              <WeekForecast
                isShown = {isShown}
                setIsShown = {setIsShown}
              >

              </WeekForecast>
            )
          }
      </main>
    </div>
  );
};

export default Home;


