import Button from "@mui/material/Button";
import type { NextPage } from "next";
import Head from "next/head";
import { WeekForecast } from "../components/week-forecast";
import styles from "../styles/Home.module.css";
import mainStyles from "../styles/mainCard.module.css";
import { useState, MouseEvent, useEffect } from "react";
import { SearchInput } from "../components/common/search";
import { Typography } from "@mui/material";
import { weatherService } from "../service/weather-service";

const Home: NextPage = () => {
  const [isShown, setIsShown] = useState(false);
  const [data, setData] = useState<any>();
  const handleClick = (event: MouseEvent<HTMLButtonElement, Event>) => {
    setIsShown((current: boolean) => !current);
  };

  useEffect(() => {
    new weatherService()
      .getAll("london")
      .then((response) => {
        setData(response.data);
      })
      .catch((error) => {
        console.log(error);
      })
      .finally(() => {
        console.log("Data traida exitosamente");
      });
  }, []);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {!isShown && (
          <div
            className={`${mainStyles.card} ${mainStyles.mainCard} ${mainStyles.swingBottom}`}
          >
            <h1>clyma</h1>
            <h3>Updated just now</h3>

            <SearchInput></SearchInput>
            <div className={mainStyles.weatherStateContainer}>
              <Typography
                variant="h1"
                className={mainStyles.temperatureIndicator}
              >
                11°
              </Typography>
              <Typography variant="h4">Thunderstorm</Typography>
              <Typography variant="h4">Min 11° | Max:16°</Typography>
              <Typography variant="h4">3% chance of rain</Typography>
            </div>
            <div className={mainStyles.tableContainer}>
              <table className={mainStyles.table}>
                <colgroup>
                  <col className={mainStyles.colRight} />
                  <col className={mainStyles.colLeft} />
                </colgroup>
                <tr className={mainStyles.tableText}>
                  <td>Humidity</td>
                  <td>58%</td>
                </tr>
                <tr>
                  <td className={mainStyles.tableText}>Pressure</td>
                  <td>1018 mB</td>
                </tr>
                <tr>
                  <td className={mainStyles.tableText}>Wind Speed</td>
                  <td>15 km/h</td>
                </tr>
              </table>
            </div>
            <Button
              onClick={(e) => handleClick(e)}
              variant="contained"
              size="large"
              className="mui-button"
            >
              week forecast
            </Button>
          </div>
        )}
        {isShown && (
          <WeekForecast
            isShown={isShown}
            setIsShown={setIsShown}
          ></WeekForecast>
        )}
      </main>
    </div>
  );
};

export default Home;
